export type EmojiEntry = {
  emoji: string;
  keywords: string[];
};

export type EmojiCategory = {
  name: string;
  emojis: EmojiEntry[];
};

export const emojiCategories: EmojiCategory[] = [
  {
    name: "Smileys & People",
    emojis: [
      { emoji: "😀", keywords: ["grin", "happy", "smile"] },
      { emoji: "😃", keywords: ["happy", "smile", "open"] },
      { emoji: "😄", keywords: ["happy", "smile", "laugh"] },
      { emoji: "😁", keywords: ["grin", "happy", "beam"] },
      { emoji: "😆", keywords: ["laugh", "happy", "squint"] },
      { emoji: "😅", keywords: ["sweat", "laugh", "nervous"] },
      { emoji: "🤣", keywords: ["rofl", "laugh", "rolling"] },
      { emoji: "😂", keywords: ["joy", "laugh", "tears"] },
      { emoji: "🙂", keywords: ["smile", "slight"] },
      { emoji: "😉", keywords: ["wink"] },
      { emoji: "😊", keywords: ["blush", "happy", "smile"] },
      { emoji: "😇", keywords: ["angel", "halo", "innocent"] },
      { emoji: "🥰", keywords: ["love", "hearts", "adore"] },
      { emoji: "😍", keywords: ["love", "heart", "eyes"] },
      { emoji: "🤩", keywords: ["star", "eyes", "excited"] },
      { emoji: "😘", keywords: ["kiss", "love"] },
      { emoji: "😜", keywords: ["wink", "tongue", "playful"] },
      { emoji: "🤔", keywords: ["think", "hmm", "consider"] },
      { emoji: "🤗", keywords: ["hug", "warm"] },
      { emoji: "🤫", keywords: ["quiet", "shush", "secret"] },
      { emoji: "🤭", keywords: ["oops", "giggle"] },
      { emoji: "😐", keywords: ["neutral", "blank"] },
      { emoji: "😑", keywords: ["expressionless", "blank"] },
      { emoji: "😶", keywords: ["silent", "mute", "no mouth"] },
      { emoji: "😏", keywords: ["smirk", "sly"] },
      { emoji: "😒", keywords: ["unamused", "annoyed"] },
      { emoji: "🙄", keywords: ["eye roll", "annoyed"] },
      { emoji: "😬", keywords: ["grimace", "awkward"] },
      { emoji: "😌", keywords: ["relieved", "calm", "peaceful"] },
      { emoji: "😔", keywords: ["sad", "pensive", "down"] },
      { emoji: "😴", keywords: ["sleep", "zzz", "tired"] },
      { emoji: "🤯", keywords: ["mind blown", "exploding", "shocked"] },
      { emoji: "😎", keywords: ["cool", "sunglasses"] },
      { emoji: "🥳", keywords: ["party", "celebrate", "birthday"] },
      { emoji: "😤", keywords: ["angry", "frustrated", "huff"] },
      { emoji: "😡", keywords: ["angry", "mad", "rage"] },
      { emoji: "😱", keywords: ["scream", "scared", "shocked"] },
      { emoji: "😨", keywords: ["fear", "scared"] },
      { emoji: "😢", keywords: ["cry", "sad", "tear"] },
      { emoji: "😭", keywords: ["sob", "cry", "loud"] },
      { emoji: "🤓", keywords: ["nerd", "glasses", "geek"] },
      { emoji: "🧐", keywords: ["monocle", "inspect", "curious"] },
      { emoji: "🥺", keywords: ["pleading", "puppy", "please"] },
      { emoji: "🤡", keywords: ["clown"] },
      { emoji: "👻", keywords: ["ghost", "spooky", "halloween"] },
      { emoji: "💀", keywords: ["skull", "dead", "death"] },
      { emoji: "👋", keywords: ["wave", "hello", "bye"] },
      { emoji: "👍", keywords: ["thumbs up", "like", "approve", "yes"] },
      { emoji: "👎", keywords: ["thumbs down", "dislike", "no"] },
      { emoji: "👏", keywords: ["clap", "applause", "bravo"] },
      { emoji: "🙌", keywords: ["hands", "celebrate", "hooray"] },
      { emoji: "🤝", keywords: ["handshake", "deal", "agree"] },
      { emoji: "💪", keywords: ["strong", "muscle", "flex"] },
      { emoji: "🧠", keywords: ["brain", "smart", "think"] },
    ],
  },
  {
    name: "Animals & Nature",
    emojis: [
      { emoji: "🐶", keywords: ["dog", "puppy", "pet"] },
      { emoji: "🐱", keywords: ["cat", "kitten", "pet"] },
      { emoji: "🐭", keywords: ["mouse", "rodent"] },
      { emoji: "🐹", keywords: ["hamster", "pet"] },
      { emoji: "🐰", keywords: ["rabbit", "bunny"] },
      { emoji: "🦊", keywords: ["fox"] },
      { emoji: "🐻", keywords: ["bear"] },
      { emoji: "🐼", keywords: ["panda", "bear"] },
      { emoji: "🐨", keywords: ["koala"] },
      { emoji: "🐯", keywords: ["tiger"] },
      { emoji: "🦁", keywords: ["lion", "king"] },
      { emoji: "🐸", keywords: ["frog"] },
      { emoji: "🐵", keywords: ["monkey"] },
      { emoji: "🐔", keywords: ["chicken"] },
      { emoji: "🐧", keywords: ["penguin"] },
      { emoji: "🐦", keywords: ["bird"] },
      { emoji: "🦅", keywords: ["eagle", "bird"] },
      { emoji: "🦋", keywords: ["butterfly", "insect"] },
      { emoji: "🐛", keywords: ["bug", "insect"] },
      { emoji: "🐝", keywords: ["bee", "honey"] },
      { emoji: "🐞", keywords: ["ladybug", "bug"] },
      { emoji: "🐢", keywords: ["turtle", "slow"] },
      { emoji: "🐍", keywords: ["snake"] },
      { emoji: "🐙", keywords: ["octopus"] },
      { emoji: "🦀", keywords: ["crab"] },
      { emoji: "🐬", keywords: ["dolphin", "ocean"] },
      { emoji: "🐳", keywords: ["whale", "ocean"] },
      { emoji: "🌸", keywords: ["cherry blossom", "flower", "spring"] },
      { emoji: "🌹", keywords: ["rose", "flower", "love"] },
      { emoji: "🌻", keywords: ["sunflower", "flower"] },
      { emoji: "🌲", keywords: ["evergreen", "tree", "nature"] },
      { emoji: "🌿", keywords: ["herb", "plant", "leaf", "green"] },
      { emoji: "🍀", keywords: ["clover", "luck", "four leaf"] },
      { emoji: "🍁", keywords: ["maple", "leaf", "fall", "autumn"] },
      { emoji: "🌈", keywords: ["rainbow"] },
      { emoji: "☀️", keywords: ["sun", "sunny", "bright"] },
      { emoji: "🌙", keywords: ["moon", "night", "crescent"] },
      { emoji: "⭐", keywords: ["star", "favorite"] },
      { emoji: "🌊", keywords: ["wave", "ocean", "water"] },
      { emoji: "❄️", keywords: ["snowflake", "cold", "winter"] },
    ],
  },
  {
    name: "Food & Drink",
    emojis: [
      { emoji: "🍎", keywords: ["apple", "red", "fruit"] },
      { emoji: "🍊", keywords: ["orange", "fruit"] },
      { emoji: "🍋", keywords: ["lemon", "citrus", "sour"] },
      { emoji: "🍇", keywords: ["grapes", "fruit"] },
      { emoji: "🍓", keywords: ["strawberry", "fruit", "berry"] },
      { emoji: "🍑", keywords: ["peach", "fruit"] },
      { emoji: "🍌", keywords: ["banana", "fruit"] },
      { emoji: "🥑", keywords: ["avocado", "fruit"] },
      { emoji: "🍕", keywords: ["pizza", "food"] },
      { emoji: "🍔", keywords: ["burger", "hamburger", "food"] },
      { emoji: "🌮", keywords: ["taco", "food", "mexican"] },
      { emoji: "🍜", keywords: ["noodles", "ramen", "soup"] },
      { emoji: "🍣", keywords: ["sushi", "japanese", "food"] },
      { emoji: "🍩", keywords: ["donut", "dessert", "sweet"] },
      { emoji: "🍪", keywords: ["cookie", "dessert", "sweet"] },
      { emoji: "🎂", keywords: ["cake", "birthday", "dessert"] },
      { emoji: "🍰", keywords: ["cake", "slice", "dessert"] },
      { emoji: "🍫", keywords: ["chocolate", "candy", "sweet"] },
      { emoji: "☕", keywords: ["coffee", "drink", "hot"] },
      { emoji: "🍵", keywords: ["tea", "drink", "green"] },
      { emoji: "🧃", keywords: ["juice", "drink", "box"] },
      { emoji: "🍺", keywords: ["beer", "drink", "alcohol"] },
      { emoji: "🍷", keywords: ["wine", "drink", "alcohol"] },
      { emoji: "🥤", keywords: ["cup", "drink", "soda"] },
    ],
  },
  {
    name: "Activities",
    emojis: [
      { emoji: "⚽", keywords: ["soccer", "football", "sport"] },
      { emoji: "🏀", keywords: ["basketball", "sport"] },
      { emoji: "🏈", keywords: ["football", "american", "sport"] },
      { emoji: "⚾", keywords: ["baseball", "sport"] },
      { emoji: "🎾", keywords: ["tennis", "sport"] },
      { emoji: "🏐", keywords: ["volleyball", "sport"] },
      { emoji: "🎮", keywords: ["game", "video game", "controller"] },
      { emoji: "🎲", keywords: ["dice", "game", "random"] },
      { emoji: "🧩", keywords: ["puzzle", "piece", "jigsaw"] },
      { emoji: "🎯", keywords: ["target", "dart", "bullseye", "goal"] },
      { emoji: "🎳", keywords: ["bowling", "sport"] },
      { emoji: "🎸", keywords: ["guitar", "music", "rock"] },
      { emoji: "🎹", keywords: ["piano", "music", "keys"] },
      { emoji: "🎤", keywords: ["microphone", "sing", "karaoke"] },
      { emoji: "🎬", keywords: ["movie", "film", "cinema", "clapper"] },
      { emoji: "🎨", keywords: ["art", "paint", "palette", "creative"] },
      { emoji: "🎭", keywords: ["theater", "drama", "masks"] },
      { emoji: "🏆", keywords: ["trophy", "win", "champion", "award"] },
      { emoji: "🥇", keywords: ["gold", "medal", "first", "winner"] },
      { emoji: "🎪", keywords: ["circus", "tent"] },
      { emoji: "🎰", keywords: ["slot", "machine", "casino"] },
    ],
  },
  {
    name: "Travel & Places",
    emojis: [
      { emoji: "🚗", keywords: ["car", "drive", "vehicle"] },
      { emoji: "🚕", keywords: ["taxi", "cab"] },
      { emoji: "🚀", keywords: ["rocket", "launch", "space"] },
      { emoji: "✈️", keywords: ["airplane", "plane", "travel", "flight"] },
      { emoji: "🚂", keywords: ["train", "locomotive"] },
      { emoji: "🚢", keywords: ["ship", "boat", "cruise"] },
      { emoji: "🏠", keywords: ["house", "home"] },
      { emoji: "🏢", keywords: ["office", "building", "work"] },
      { emoji: "🏫", keywords: ["school", "building", "education"] },
      { emoji: "🏥", keywords: ["hospital", "medical", "health"] },
      { emoji: "⛪", keywords: ["church", "building", "religion"] },
      { emoji: "🏰", keywords: ["castle", "palace"] },
      { emoji: "🗽", keywords: ["statue of liberty", "new york"] },
      { emoji: "🗼", keywords: ["tokyo tower", "tower"] },
      { emoji: "🌍", keywords: ["earth", "globe", "world", "europe", "africa"] },
      { emoji: "🏖️", keywords: ["beach", "umbrella", "vacation"] },
      { emoji: "🏔️", keywords: ["mountain", "snow", "peak"] },
      { emoji: "⛺", keywords: ["tent", "camping", "outdoors"] },
    ],
  },
  {
    name: "Objects",
    emojis: [
      { emoji: "💡", keywords: ["idea", "light", "bulb"] },
      { emoji: "🔑", keywords: ["key", "lock", "password"] },
      { emoji: "🔒", keywords: ["lock", "secure", "private"] },
      { emoji: "🔓", keywords: ["unlock", "open"] },
      { emoji: "📱", keywords: ["phone", "mobile", "cell"] },
      { emoji: "💻", keywords: ["laptop", "computer"] },
      { emoji: "🖥️", keywords: ["desktop", "computer", "monitor"] },
      { emoji: "📷", keywords: ["camera", "photo"] },
      { emoji: "📚", keywords: ["books", "library", "read", "study"] },
      { emoji: "📝", keywords: ["memo", "note", "write", "pencil"] },
      { emoji: "📅", keywords: ["calendar", "date", "schedule"] },
      { emoji: "📌", keywords: ["pin", "pushpin", "location"] },
      { emoji: "📎", keywords: ["paperclip", "attach"] },
      { emoji: "✏️", keywords: ["pencil", "write", "edit"] },
      { emoji: "🔧", keywords: ["wrench", "tool", "fix", "settings"] },
      { emoji: "🔨", keywords: ["hammer", "tool", "build"] },
      { emoji: "⚙️", keywords: ["gear", "settings", "config"] },
      { emoji: "🧲", keywords: ["magnet"] },
      { emoji: "💎", keywords: ["gem", "diamond", "precious"] },
      { emoji: "🎁", keywords: ["gift", "present", "wrapped"] },
      { emoji: "🏷️", keywords: ["tag", "label", "price"] },
      { emoji: "💰", keywords: ["money", "bag", "dollar"] },
      { emoji: "⏰", keywords: ["alarm", "clock", "time", "wake"] },
      { emoji: "⌛", keywords: ["hourglass", "time", "wait"] },
      { emoji: "🔔", keywords: ["bell", "notification", "alert"] },
      { emoji: "📦", keywords: ["package", "box", "delivery"] },
    ],
  },
  {
    name: "Symbols",
    emojis: [
      { emoji: "❤️", keywords: ["heart", "love", "red"] },
      { emoji: "🧡", keywords: ["heart", "orange"] },
      { emoji: "💛", keywords: ["heart", "yellow"] },
      { emoji: "💚", keywords: ["heart", "green"] },
      { emoji: "💙", keywords: ["heart", "blue"] },
      { emoji: "💜", keywords: ["heart", "purple"] },
      { emoji: "🖤", keywords: ["heart", "black"] },
      { emoji: "🤍", keywords: ["heart", "white"] },
      { emoji: "💔", keywords: ["broken heart", "sad"] },
      { emoji: "❗", keywords: ["exclamation", "important", "alert"] },
      { emoji: "❓", keywords: ["question", "help", "ask"] },
      { emoji: "‼️", keywords: ["double exclamation", "urgent"] },
      { emoji: "⚠️", keywords: ["warning", "caution", "alert"] },
      { emoji: "✅", keywords: ["check", "done", "complete", "yes"] },
      { emoji: "❌", keywords: ["cross", "no", "wrong", "delete"] },
      { emoji: "⭕", keywords: ["circle", "ring", "o"] },
      { emoji: "🔴", keywords: ["red", "circle", "stop"] },
      { emoji: "🟢", keywords: ["green", "circle", "go"] },
      { emoji: "🔵", keywords: ["blue", "circle"] },
      { emoji: "🟡", keywords: ["yellow", "circle"] },
      { emoji: "🟠", keywords: ["orange", "circle"] },
      { emoji: "🟣", keywords: ["purple", "circle"] },
      { emoji: "⬆️", keywords: ["up", "arrow"] },
      { emoji: "⬇️", keywords: ["down", "arrow"] },
      { emoji: "➡️", keywords: ["right", "arrow", "next"] },
      { emoji: "⬅️", keywords: ["left", "arrow", "back"] },
      { emoji: "🔥", keywords: ["fire", "hot", "lit", "flame"] },
      { emoji: "💯", keywords: ["hundred", "perfect", "score"] },
      { emoji: "✨", keywords: ["sparkles", "shine", "magic", "new"] },
      { emoji: "💫", keywords: ["dizzy", "star", "shooting"] },
      { emoji: "🎉", keywords: ["party", "tada", "celebrate", "congrats"] },
      { emoji: "🎊", keywords: ["confetti", "celebrate"] },
      { emoji: "💬", keywords: ["speech", "bubble", "chat", "comment"] },
      { emoji: "💭", keywords: ["thought", "bubble", "think"] },
      { emoji: "🚫", keywords: ["prohibited", "no", "forbidden", "ban"] },
      { emoji: "♻️", keywords: ["recycle", "green", "environment"] },
      { emoji: "🔗", keywords: ["link", "chain", "url"] },
      { emoji: "ℹ️", keywords: ["info", "information"] },
    ],
  },
  {
    name: "Flags",
    emojis: [
      { emoji: "🏁", keywords: ["checkered", "flag", "finish", "race"] },
      { emoji: "🚩", keywords: ["red flag", "triangular"] },
      { emoji: "🏳️", keywords: ["white flag", "surrender"] },
      { emoji: "🏴", keywords: ["black flag"] },
      { emoji: "🎌", keywords: ["crossed flags", "japan"] },
      { emoji: "🏴‍☠️", keywords: ["pirate", "flag", "jolly roger"] },
    ],
  },
];

export function searchEmojis(query: string): EmojiEntry[] {
  const lower = query.toLowerCase().trim();
  if (!lower) return [];
  const results: EmojiEntry[] = [];
  for (const category of emojiCategories) {
    for (const entry of category.emojis) {
      if (entry.keywords.some((k) => k.includes(lower))) {
        results.push(entry);
      }
    }
  }
  return results;
}

export function splitEmojis(emojiString: string): string[] {
  if (!emojiString) return [];
  return [...emojiString];
}
