/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WIndexRouteImport } from './routes/w/index'
import { Route as WWorkspaceIdRouteRouteImport } from './routes/w/$workspaceId/route'
import { Route as WWorkspaceIdIndexRouteImport } from './routes/w/$workspaceId/index'
import { Route as WWorkspaceIdUpcomingRouteImport } from './routes/w/$workspaceId/upcoming'
import { Route as WWorkspaceIdSyncRouteImport } from './routes/w/$workspaceId/sync'
import { Route as WWorkspaceIdSettingsRouteImport } from './routes/w/$workspaceId/settings'
import { Route as WWorkspaceIdProjectsRouteImport } from './routes/w/$workspaceId/projects'
import { Route as WWorkspaceIdPProjectIdRouteRouteImport } from './routes/w/$workspaceId/p/$projectId/route'
import { Route as WWorkspaceIdPProjectIdIndexRouteImport } from './routes/w/$workspaceId/p/$projectId/index'
import { Route as WWorkspaceIdPProjectIdWorkspaceSettingsRouteImport } from './routes/w/$workspaceId/p/$projectId/workspace-settings'
import { Route as WWorkspaceIdPProjectIdSyncRouteImport } from './routes/w/$workspaceId/p/$projectId/sync'
import { Route as WWorkspaceIdPProjectIdSettingsRouteImport } from './routes/w/$workspaceId/p/$projectId/settings'
import { Route as WWorkspaceIdPProjectIdTasksRouteRouteImport } from './routes/w/$workspaceId/p/$projectId/tasks/route'
import { Route as WWorkspaceIdPProjectIdKanbanRouteRouteImport } from './routes/w/$workspaceId/p/$projectId/kanban/route'
import { Route as WWorkspaceIdPProjectIdTasksIndexRouteImport } from './routes/w/$workspaceId/p/$projectId/tasks/index'
import { Route as WWorkspaceIdPProjectIdKanbanIndexRouteImport } from './routes/w/$workspaceId/p/$projectId/kanban/index'
import { Route as WWorkspaceIdPProjectIdTasksTaskIdRouteImport } from './routes/w/$workspaceId/p/$projectId/tasks/$taskId'
import { Route as WWorkspaceIdPProjectIdKanbanTaskIdRouteImport } from './routes/w/$workspaceId/p/$projectId/kanban/$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WIndexRoute = WIndexRouteImport.update({
  id: '/w/',
  path: '/w/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdRouteRoute = WWorkspaceIdRouteRouteImport.update({
  id: '/w/$workspaceId',
  path: '/w/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdIndexRoute = WWorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWorkspaceIdRouteRoute,
} as any)
const WWorkspaceIdUpcomingRoute = WWorkspaceIdUpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => WWorkspaceIdRouteRoute,
} as any)
const WWorkspaceIdSyncRoute = WWorkspaceIdSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => WWorkspaceIdRouteRoute,
} as any)
const WWorkspaceIdSettingsRoute = WWorkspaceIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WWorkspaceIdRouteRoute,
} as any)
const WWorkspaceIdProjectsRoute = WWorkspaceIdProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => WWorkspaceIdRouteRoute,
} as any)
const WWorkspaceIdPProjectIdRouteRoute =
  WWorkspaceIdPProjectIdRouteRouteImport.update({
    id: '/p/$projectId',
    path: '/p/$projectId',
    getParentRoute: () => WWorkspaceIdRouteRoute,
  } as any)
const WWorkspaceIdPProjectIdIndexRoute =
  WWorkspaceIdPProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WWorkspaceIdPProjectIdRouteRoute,
  } as any)
const WWorkspaceIdPProjectIdWorkspaceSettingsRoute =
  WWorkspaceIdPProjectIdWorkspaceSettingsRouteImport.update({
    id: '/workspace-settings',
    path: '/workspace-settings',
    getParentRoute: () => WWorkspaceIdPProjectIdRouteRoute,
  } as any)
const WWorkspaceIdPProjectIdSyncRoute =
  WWorkspaceIdPProjectIdSyncRouteImport.update({
    id: '/sync',
    path: '/sync',
    getParentRoute: () => WWorkspaceIdPProjectIdRouteRoute,
  } as any)
const WWorkspaceIdPProjectIdSettingsRoute =
  WWorkspaceIdPProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WWorkspaceIdPProjectIdRouteRoute,
  } as any)
const WWorkspaceIdPProjectIdTasksRouteRoute =
  WWorkspaceIdPProjectIdTasksRouteRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => WWorkspaceIdPProjectIdRouteRoute,
  } as any)
const WWorkspaceIdPProjectIdKanbanRouteRoute =
  WWorkspaceIdPProjectIdKanbanRouteRouteImport.update({
    id: '/kanban',
    path: '/kanban',
    getParentRoute: () => WWorkspaceIdPProjectIdRouteRoute,
  } as any)
const WWorkspaceIdPProjectIdTasksIndexRoute =
  WWorkspaceIdPProjectIdTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WWorkspaceIdPProjectIdTasksRouteRoute,
  } as any)
const WWorkspaceIdPProjectIdKanbanIndexRoute =
  WWorkspaceIdPProjectIdKanbanIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WWorkspaceIdPProjectIdKanbanRouteRoute,
  } as any)
const WWorkspaceIdPProjectIdTasksTaskIdRoute =
  WWorkspaceIdPProjectIdTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => WWorkspaceIdPProjectIdTasksRouteRoute,
  } as any)
const WWorkspaceIdPProjectIdKanbanTaskIdRoute =
  WWorkspaceIdPProjectIdKanbanTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => WWorkspaceIdPProjectIdKanbanRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/w/$workspaceId': typeof WWorkspaceIdRouteRouteWithChildren
  '/w/': typeof WIndexRoute
  '/w/$workspaceId/projects': typeof WWorkspaceIdProjectsRoute
  '/w/$workspaceId/settings': typeof WWorkspaceIdSettingsRoute
  '/w/$workspaceId/sync': typeof WWorkspaceIdSyncRoute
  '/w/$workspaceId/upcoming': typeof WWorkspaceIdUpcomingRoute
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/p/$projectId': typeof WWorkspaceIdPProjectIdRouteRouteWithChildren
  '/w/$workspaceId/p/$projectId/kanban': typeof WWorkspaceIdPProjectIdKanbanRouteRouteWithChildren
  '/w/$workspaceId/p/$projectId/tasks': typeof WWorkspaceIdPProjectIdTasksRouteRouteWithChildren
  '/w/$workspaceId/p/$projectId/settings': typeof WWorkspaceIdPProjectIdSettingsRoute
  '/w/$workspaceId/p/$projectId/sync': typeof WWorkspaceIdPProjectIdSyncRoute
  '/w/$workspaceId/p/$projectId/workspace-settings': typeof WWorkspaceIdPProjectIdWorkspaceSettingsRoute
  '/w/$workspaceId/p/$projectId/': typeof WWorkspaceIdPProjectIdIndexRoute
  '/w/$workspaceId/p/$projectId/kanban/$taskId': typeof WWorkspaceIdPProjectIdKanbanTaskIdRoute
  '/w/$workspaceId/p/$projectId/tasks/$taskId': typeof WWorkspaceIdPProjectIdTasksTaskIdRoute
  '/w/$workspaceId/p/$projectId/kanban/': typeof WWorkspaceIdPProjectIdKanbanIndexRoute
  '/w/$workspaceId/p/$projectId/tasks/': typeof WWorkspaceIdPProjectIdTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/w': typeof WIndexRoute
  '/w/$workspaceId/projects': typeof WWorkspaceIdProjectsRoute
  '/w/$workspaceId/settings': typeof WWorkspaceIdSettingsRoute
  '/w/$workspaceId/sync': typeof WWorkspaceIdSyncRoute
  '/w/$workspaceId/upcoming': typeof WWorkspaceIdUpcomingRoute
  '/w/$workspaceId': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/p/$projectId/settings': typeof WWorkspaceIdPProjectIdSettingsRoute
  '/w/$workspaceId/p/$projectId/sync': typeof WWorkspaceIdPProjectIdSyncRoute
  '/w/$workspaceId/p/$projectId/workspace-settings': typeof WWorkspaceIdPProjectIdWorkspaceSettingsRoute
  '/w/$workspaceId/p/$projectId': typeof WWorkspaceIdPProjectIdIndexRoute
  '/w/$workspaceId/p/$projectId/kanban/$taskId': typeof WWorkspaceIdPProjectIdKanbanTaskIdRoute
  '/w/$workspaceId/p/$projectId/tasks/$taskId': typeof WWorkspaceIdPProjectIdTasksTaskIdRoute
  '/w/$workspaceId/p/$projectId/kanban': typeof WWorkspaceIdPProjectIdKanbanIndexRoute
  '/w/$workspaceId/p/$projectId/tasks': typeof WWorkspaceIdPProjectIdTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/w/$workspaceId': typeof WWorkspaceIdRouteRouteWithChildren
  '/w/': typeof WIndexRoute
  '/w/$workspaceId/projects': typeof WWorkspaceIdProjectsRoute
  '/w/$workspaceId/settings': typeof WWorkspaceIdSettingsRoute
  '/w/$workspaceId/sync': typeof WWorkspaceIdSyncRoute
  '/w/$workspaceId/upcoming': typeof WWorkspaceIdUpcomingRoute
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/p/$projectId': typeof WWorkspaceIdPProjectIdRouteRouteWithChildren
  '/w/$workspaceId/p/$projectId/kanban': typeof WWorkspaceIdPProjectIdKanbanRouteRouteWithChildren
  '/w/$workspaceId/p/$projectId/tasks': typeof WWorkspaceIdPProjectIdTasksRouteRouteWithChildren
  '/w/$workspaceId/p/$projectId/settings': typeof WWorkspaceIdPProjectIdSettingsRoute
  '/w/$workspaceId/p/$projectId/sync': typeof WWorkspaceIdPProjectIdSyncRoute
  '/w/$workspaceId/p/$projectId/workspace-settings': typeof WWorkspaceIdPProjectIdWorkspaceSettingsRoute
  '/w/$workspaceId/p/$projectId/': typeof WWorkspaceIdPProjectIdIndexRoute
  '/w/$workspaceId/p/$projectId/kanban/$taskId': typeof WWorkspaceIdPProjectIdKanbanTaskIdRoute
  '/w/$workspaceId/p/$projectId/tasks/$taskId': typeof WWorkspaceIdPProjectIdTasksTaskIdRoute
  '/w/$workspaceId/p/$projectId/kanban/': typeof WWorkspaceIdPProjectIdKanbanIndexRoute
  '/w/$workspaceId/p/$projectId/tasks/': typeof WWorkspaceIdPProjectIdTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/w/$workspaceId'
    | '/w/'
    | '/w/$workspaceId/projects'
    | '/w/$workspaceId/settings'
    | '/w/$workspaceId/sync'
    | '/w/$workspaceId/upcoming'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/p/$projectId'
    | '/w/$workspaceId/p/$projectId/kanban'
    | '/w/$workspaceId/p/$projectId/tasks'
    | '/w/$workspaceId/p/$projectId/settings'
    | '/w/$workspaceId/p/$projectId/sync'
    | '/w/$workspaceId/p/$projectId/workspace-settings'
    | '/w/$workspaceId/p/$projectId/'
    | '/w/$workspaceId/p/$projectId/kanban/$taskId'
    | '/w/$workspaceId/p/$projectId/tasks/$taskId'
    | '/w/$workspaceId/p/$projectId/kanban/'
    | '/w/$workspaceId/p/$projectId/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/w'
    | '/w/$workspaceId/projects'
    | '/w/$workspaceId/settings'
    | '/w/$workspaceId/sync'
    | '/w/$workspaceId/upcoming'
    | '/w/$workspaceId'
    | '/w/$workspaceId/p/$projectId/settings'
    | '/w/$workspaceId/p/$projectId/sync'
    | '/w/$workspaceId/p/$projectId/workspace-settings'
    | '/w/$workspaceId/p/$projectId'
    | '/w/$workspaceId/p/$projectId/kanban/$taskId'
    | '/w/$workspaceId/p/$projectId/tasks/$taskId'
    | '/w/$workspaceId/p/$projectId/kanban'
    | '/w/$workspaceId/p/$projectId/tasks'
  id:
    | '__root__'
    | '/'
    | '/w/$workspaceId'
    | '/w/'
    | '/w/$workspaceId/projects'
    | '/w/$workspaceId/settings'
    | '/w/$workspaceId/sync'
    | '/w/$workspaceId/upcoming'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/p/$projectId'
    | '/w/$workspaceId/p/$projectId/kanban'
    | '/w/$workspaceId/p/$projectId/tasks'
    | '/w/$workspaceId/p/$projectId/settings'
    | '/w/$workspaceId/p/$projectId/sync'
    | '/w/$workspaceId/p/$projectId/workspace-settings'
    | '/w/$workspaceId/p/$projectId/'
    | '/w/$workspaceId/p/$projectId/kanban/$taskId'
    | '/w/$workspaceId/p/$projectId/tasks/$taskId'
    | '/w/$workspaceId/p/$projectId/kanban/'
    | '/w/$workspaceId/p/$projectId/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WWorkspaceIdRouteRoute: typeof WWorkspaceIdRouteRouteWithChildren
  WIndexRoute: typeof WIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/': {
      id: '/w/'
      path: '/w'
      fullPath: '/w/'
      preLoaderRoute: typeof WIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId': {
      id: '/w/$workspaceId'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId'
      preLoaderRoute: typeof WWorkspaceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId/': {
      id: '/w/$workspaceId/'
      path: '/'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof WWorkspaceIdIndexRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/upcoming': {
      id: '/w/$workspaceId/upcoming'
      path: '/upcoming'
      fullPath: '/w/$workspaceId/upcoming'
      preLoaderRoute: typeof WWorkspaceIdUpcomingRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/sync': {
      id: '/w/$workspaceId/sync'
      path: '/sync'
      fullPath: '/w/$workspaceId/sync'
      preLoaderRoute: typeof WWorkspaceIdSyncRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/settings': {
      id: '/w/$workspaceId/settings'
      path: '/settings'
      fullPath: '/w/$workspaceId/settings'
      preLoaderRoute: typeof WWorkspaceIdSettingsRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/projects': {
      id: '/w/$workspaceId/projects'
      path: '/projects'
      fullPath: '/w/$workspaceId/projects'
      preLoaderRoute: typeof WWorkspaceIdProjectsRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/p/$projectId': {
      id: '/w/$workspaceId/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/w/$workspaceId/p/$projectId'
      preLoaderRoute: typeof WWorkspaceIdPProjectIdRouteRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/p/$projectId/': {
      id: '/w/$workspaceId/p/$projectId/'
      path: '/'
      fullPath: '/w/$workspaceId/p/$projectId/'
      preLoaderRoute: typeof WWorkspaceIdPProjectIdIndexRouteImport
      parentRoute: typeof WWorkspaceIdPProjectIdRouteRoute
    }
    '/w/$workspaceId/p/$projectId/workspace-settings': {
      id: '/w/$workspaceId/p/$projectId/workspace-settings'
      path: '/workspace-settings'
      fullPath: '/w/$workspaceId/p/$projectId/workspace-settings'
      preLoaderRoute: typeof WWorkspaceIdPProjectIdWorkspaceSettingsRouteImport
      parentRoute: typeof WWorkspaceIdPProjectIdRouteRoute
    }
    '/w/$workspaceId/p/$projectId/sync': {
      id: '/w/$workspaceId/p/$projectId/sync'
      path: '/sync'
      fullPath: '/w/$workspaceId/p/$projectId/sync'
      preLoaderRoute: typeof WWorkspaceIdPProjectIdSyncRouteImport
      parentRoute: typeof WWorkspaceIdPProjectIdRouteRoute
    }
    '/w/$workspaceId/p/$projectId/settings': {
      id: '/w/$workspaceId/p/$projectId/settings'
      path: '/settings'
      fullPath: '/w/$workspaceId/p/$projectId/settings'
      preLoaderRoute: typeof WWorkspaceIdPProjectIdSettingsRouteImport
      parentRoute: typeof WWorkspaceIdPProjectIdRouteRoute
    }
    '/w/$workspaceId/p/$projectId/tasks': {
      id: '/w/$workspaceId/p/$projectId/tasks'
      path: '/tasks'
      fullPath: '/w/$workspaceId/p/$projectId/tasks'
      preLoaderRoute: typeof WWorkspaceIdPProjectIdTasksRouteRouteImport
      parentRoute: typeof WWorkspaceIdPProjectIdRouteRoute
    }
    '/w/$workspaceId/p/$projectId/kanban': {
      id: '/w/$workspaceId/p/$projectId/kanban'
      path: '/kanban'
      fullPath: '/w/$workspaceId/p/$projectId/kanban'
      preLoaderRoute: typeof WWorkspaceIdPProjectIdKanbanRouteRouteImport
      parentRoute: typeof WWorkspaceIdPProjectIdRouteRoute
    }
    '/w/$workspaceId/p/$projectId/tasks/': {
      id: '/w/$workspaceId/p/$projectId/tasks/'
      path: '/'
      fullPath: '/w/$workspaceId/p/$projectId/tasks/'
      preLoaderRoute: typeof WWorkspaceIdPProjectIdTasksIndexRouteImport
      parentRoute: typeof WWorkspaceIdPProjectIdTasksRouteRoute
    }
    '/w/$workspaceId/p/$projectId/kanban/': {
      id: '/w/$workspaceId/p/$projectId/kanban/'
      path: '/'
      fullPath: '/w/$workspaceId/p/$projectId/kanban/'
      preLoaderRoute: typeof WWorkspaceIdPProjectIdKanbanIndexRouteImport
      parentRoute: typeof WWorkspaceIdPProjectIdKanbanRouteRoute
    }
    '/w/$workspaceId/p/$projectId/tasks/$taskId': {
      id: '/w/$workspaceId/p/$projectId/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/w/$workspaceId/p/$projectId/tasks/$taskId'
      preLoaderRoute: typeof WWorkspaceIdPProjectIdTasksTaskIdRouteImport
      parentRoute: typeof WWorkspaceIdPProjectIdTasksRouteRoute
    }
    '/w/$workspaceId/p/$projectId/kanban/$taskId': {
      id: '/w/$workspaceId/p/$projectId/kanban/$taskId'
      path: '/$taskId'
      fullPath: '/w/$workspaceId/p/$projectId/kanban/$taskId'
      preLoaderRoute: typeof WWorkspaceIdPProjectIdKanbanTaskIdRouteImport
      parentRoute: typeof WWorkspaceIdPProjectIdKanbanRouteRoute
    }
  }
}

interface WWorkspaceIdPProjectIdKanbanRouteRouteChildren {
  WWorkspaceIdPProjectIdKanbanTaskIdRoute: typeof WWorkspaceIdPProjectIdKanbanTaskIdRoute
  WWorkspaceIdPProjectIdKanbanIndexRoute: typeof WWorkspaceIdPProjectIdKanbanIndexRoute
}

const WWorkspaceIdPProjectIdKanbanRouteRouteChildren: WWorkspaceIdPProjectIdKanbanRouteRouteChildren =
  {
    WWorkspaceIdPProjectIdKanbanTaskIdRoute:
      WWorkspaceIdPProjectIdKanbanTaskIdRoute,
    WWorkspaceIdPProjectIdKanbanIndexRoute:
      WWorkspaceIdPProjectIdKanbanIndexRoute,
  }

const WWorkspaceIdPProjectIdKanbanRouteRouteWithChildren =
  WWorkspaceIdPProjectIdKanbanRouteRoute._addFileChildren(
    WWorkspaceIdPProjectIdKanbanRouteRouteChildren,
  )

interface WWorkspaceIdPProjectIdTasksRouteRouteChildren {
  WWorkspaceIdPProjectIdTasksTaskIdRoute: typeof WWorkspaceIdPProjectIdTasksTaskIdRoute
  WWorkspaceIdPProjectIdTasksIndexRoute: typeof WWorkspaceIdPProjectIdTasksIndexRoute
}

const WWorkspaceIdPProjectIdTasksRouteRouteChildren: WWorkspaceIdPProjectIdTasksRouteRouteChildren =
  {
    WWorkspaceIdPProjectIdTasksTaskIdRoute:
      WWorkspaceIdPProjectIdTasksTaskIdRoute,
    WWorkspaceIdPProjectIdTasksIndexRoute:
      WWorkspaceIdPProjectIdTasksIndexRoute,
  }

const WWorkspaceIdPProjectIdTasksRouteRouteWithChildren =
  WWorkspaceIdPProjectIdTasksRouteRoute._addFileChildren(
    WWorkspaceIdPProjectIdTasksRouteRouteChildren,
  )

interface WWorkspaceIdPProjectIdRouteRouteChildren {
  WWorkspaceIdPProjectIdKanbanRouteRoute: typeof WWorkspaceIdPProjectIdKanbanRouteRouteWithChildren
  WWorkspaceIdPProjectIdTasksRouteRoute: typeof WWorkspaceIdPProjectIdTasksRouteRouteWithChildren
  WWorkspaceIdPProjectIdSettingsRoute: typeof WWorkspaceIdPProjectIdSettingsRoute
  WWorkspaceIdPProjectIdSyncRoute: typeof WWorkspaceIdPProjectIdSyncRoute
  WWorkspaceIdPProjectIdWorkspaceSettingsRoute: typeof WWorkspaceIdPProjectIdWorkspaceSettingsRoute
  WWorkspaceIdPProjectIdIndexRoute: typeof WWorkspaceIdPProjectIdIndexRoute
}

const WWorkspaceIdPProjectIdRouteRouteChildren: WWorkspaceIdPProjectIdRouteRouteChildren =
  {
    WWorkspaceIdPProjectIdKanbanRouteRoute:
      WWorkspaceIdPProjectIdKanbanRouteRouteWithChildren,
    WWorkspaceIdPProjectIdTasksRouteRoute:
      WWorkspaceIdPProjectIdTasksRouteRouteWithChildren,
    WWorkspaceIdPProjectIdSettingsRoute: WWorkspaceIdPProjectIdSettingsRoute,
    WWorkspaceIdPProjectIdSyncRoute: WWorkspaceIdPProjectIdSyncRoute,
    WWorkspaceIdPProjectIdWorkspaceSettingsRoute:
      WWorkspaceIdPProjectIdWorkspaceSettingsRoute,
    WWorkspaceIdPProjectIdIndexRoute: WWorkspaceIdPProjectIdIndexRoute,
  }

const WWorkspaceIdPProjectIdRouteRouteWithChildren =
  WWorkspaceIdPProjectIdRouteRoute._addFileChildren(
    WWorkspaceIdPProjectIdRouteRouteChildren,
  )

interface WWorkspaceIdRouteRouteChildren {
  WWorkspaceIdProjectsRoute: typeof WWorkspaceIdProjectsRoute
  WWorkspaceIdSettingsRoute: typeof WWorkspaceIdSettingsRoute
  WWorkspaceIdSyncRoute: typeof WWorkspaceIdSyncRoute
  WWorkspaceIdUpcomingRoute: typeof WWorkspaceIdUpcomingRoute
  WWorkspaceIdIndexRoute: typeof WWorkspaceIdIndexRoute
  WWorkspaceIdPProjectIdRouteRoute: typeof WWorkspaceIdPProjectIdRouteRouteWithChildren
}

const WWorkspaceIdRouteRouteChildren: WWorkspaceIdRouteRouteChildren = {
  WWorkspaceIdProjectsRoute: WWorkspaceIdProjectsRoute,
  WWorkspaceIdSettingsRoute: WWorkspaceIdSettingsRoute,
  WWorkspaceIdSyncRoute: WWorkspaceIdSyncRoute,
  WWorkspaceIdUpcomingRoute: WWorkspaceIdUpcomingRoute,
  WWorkspaceIdIndexRoute: WWorkspaceIdIndexRoute,
  WWorkspaceIdPProjectIdRouteRoute:
    WWorkspaceIdPProjectIdRouteRouteWithChildren,
}

const WWorkspaceIdRouteRouteWithChildren =
  WWorkspaceIdRouteRoute._addFileChildren(WWorkspaceIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WWorkspaceIdRouteRoute: WWorkspaceIdRouteRouteWithChildren,
  WIndexRoute: WIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
